config/routes.rb
Rails.application.routes.draw do
  root "agendas#index"

    resources :agendas do
      resources :tasks, :notes
    end
end

app/models/agenda.rb
class Agenda < ApplicationRecord
  has_many :tasks
  has_many :notes

  validates :day, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :agenda
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  validates :category, presence: true
end

app/controllers/agendas_controller.rb
class AgendasController < ApplicationController
  def index
    @agendas = Agenda.all
  end

  def show
    @agenda = Agenda.find(params[:id])
  end

  def new
    @agenda = Agenda.new
  end

  def create
    @agenda = Agenda.new(agenda_params)

   if @agenda.save
     redirect_to @agenda
   else
     render :new
   end
  end

  def edit
    @agenda = Agenda.find(params[:id])
  end

  def update
    @agenda = Agenda.find(params[:id])

    if @agenda.update(agenda_params)
      redirect_to @agenda
    else
      render :edit
    end
  end

  private
    def agenda_params
      params.require(:agenda).permit(:day)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end

  def show
  end

  def _form
  end

  def edit
  end

  def new
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
      @agenda = Agenda.find(params[:agenda_id])
      @note = @agenda.notes.create(note_params)
      redirect_to agenda_path(@agenda)
    end

    private
      def note_params
        params.require(:note).permit(:body)
      end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def create
    @agenda = Agenda.find(params[:agenda_id])
    @task = @agenda.tasks.create(task_params)
    redirect_to agenda_path(@agenda)
  end

  def destroy
    @agenda = Agenda.find(params[:agenda_id])
    @task = @agenda.tasks.find(params[:id])
    @task.destroy
    redirect_to agenda_path(@agenda)
  end

  private
    def task_params
      params.require(:task).permit(:name, :description, :code, :due_date)
    end
end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/agendas/_form.html.erb
<%= form_with model: @agenda do |form| %>
  <div>
    <%= form.label :day %><br>
    <%= form.text_field :day %>
    <% @agenda.errors.full_messages_for(:day).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/agendas/edit.html.erb
<h1>Edit Day</h1>

<%= render "form", agenda: @agenda %>

app/views/agendas/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
* {box-sizing: border-box;}
ul {list-style-type: none;}
body {font-family: "Tahoma", sans-serif }

.colorLink {
  color: #5196BD;
}

.month {
  padding: 20px 25px;
  width: 950px;
  height: 70px;
  background: #FF5733 ;
  text-align: center;
  font-family: AM;
  font-size:13px;
  border-radius: 10px;
}

.month ul {
  margin: 1;
  padding: 0;
}

.month ul li {
  color: black;
  font-size: 20px;
  text-transform: uppercase;
  letter-spacing: 10px;
  border-radius: 6px;
}

.month .prev {
  float: left;
  padding-top: 10px;
}

.month .next {
  float: right;
  padding-top: 10px;
}

.weekdays {
  margin: 0;
  width: 950px;
  height: 55px;
  padding: 15px 0;
  background-color:#FA9B65 ;
  border-radius: 10px;
  font-family: monospace bold;
}

.weekdays li {
  display: inline-block;
  width: 13.6%;
  color: #666;
  text-align: center;
}

.days {
  padding: 30px 0;
  width: 950px;
  height: 370px;
  background: #40998E;
  margin: 0;
  border-radius: 10px;
  border: 2px solid black;
}
.hoja2
{
  
}

.days li {
  list-style-type: none;
  display: inline-block;
  width: 13.6%;
  text-align: center;
  margin-bottom: 40px;
  font-size:12px;
  font-family: Arial Black;
  color: black;
}

.days li .active {
  padding: 5px;
  background: #1abc9c;
  color: white
}
.btn btn-outline-dark
{
  border-color:none;
}

(max-width:720px) {
  .weekdays li, .days li {width: 13.1%;}
}

(max-width: 420px) {
  .weekdays li, .days li {width: 12.5%;}
  .days li .active {padding: 2px;}
}

(max-width: 290px) {
  .weekdays li, .days li {width: 12.2;}
}
.bgcolor
{
  background: #C2F3ED;
}

</style>
</head>
<body class="bgcolor">
<p></p>
<center>
<div class=".hoja2">
<center>
<div class="month">
  <ul>
    <li><font color="black">
     -- DICIEMBRE 2021 -- </span>
      </font>
    </li>
  </ul>
</div>
</center>

<ul class="weekdays">
  <li><font color="black"><b>L</b></font></li>
  <li><font color="black"><b>M</b></font></li>
  <li><font color="black"><b>M</b></font></li>
  <li><font color="black"><b>J</b></font></li>
  <li><font color="black"><b>V</b></font></li>
  <li><font color="black"><b>S</b></font></li>
  <li><font color="black"><b>D</b></font></li>
</ul>

<ul class="days">

  <li>29</li>
  <li>30</li>
  <% @agendas.each do |agenda| %>
  <li>
  <font color="black">
    <%= link_to agenda.day, agenda, class: "colorLink", class: "btn btn-light" %>
    </font>
    </li>
<% end %>
<li>01</li>
<li>02</li>
<li>03</li>
<li>04</li>
<li>05</li>
<li>06</li>
<li>07</li>
<li>08</li>
<li>09</li>
<li>10</li>
<li>11</li>
<li>12</li>
<li>13</li>
<li>14</li>
<li>15</li>
<li>16</li>
<li>17</li>
<li>18</li>
<li>19</li>
<li>20</li>
<li>21</li>
<li>22</li>
<li>23</li>
<li>24</li>
<li>25</li>
<li>26</li> 




<!--<%= link_to "New Day", new_agenda_path %>-->
</div>
</body>
</html>

app/views/agendas/new.html.erb
<style>
.bgcolor
{
  background: #c2c2c2;
}

</style>
<body class="bgcolor">

<h1>New Day</h1>

<%= render "form", agenda: @agenda %>
</body>

app/views/agendas/show.html.erb
<style media="screen">
  .backr {
    padding: 5px 0;
    background: #5DADE2;
    margin: 0;
  }
  .pad {
    padding: 30px;
  }

  body {
    font-family: "Tahoma", sans-serif
   }

   .bgcolor
   {
     background: #5DADE2;
   }
   .colors
   {
     background: #45B39D;
     height: 40px;
     width: 350px;
     font-size: 15px;
     font-family: monospace bold;
     border-radius: 3px;
     padding: 7px;
   }
   
   form
   {
   }
   </style>
<body class="bgcolor">
<div class="backr">

<!--<li><%= link_to "Edit", edit_agenda_path(@agenda) %></li> -->

<div align="left" class="pad">
<h3>Tasks:</h3>
<br></br>

<% @agenda.tasks.each do |task| %>

  <div class="container">
  <div class="row g-1">
    <div class="col-12">
      <div class="colors">
          <p>
            <strong>Name:</strong>
            <%= task.name %>
          </p>
        </div>
    </div>
    <p></p>
    <div class="col-12">
      <div class="colors">
        <p>
          <strong>Description:</strong>
          <%= task.description %>
        </p>
      </div>
    </div>
    <p></p>
    <div class="col-12">
      <div class="colors">
        <p>
          <strong>Code:</strong>
          <%= task.code %>
        </p>
      </div>
    </div>
    <p></p>
    <div class="col-12">
      <div class="colors">
        <p>
          <strong>Due_date:</strong>
          <%= task.due_date %>
        </p>
      </div>
    </div>
  </div>
</div>
<br></br>
<% end %>
<h3>Notes:</h3>
<p></p>
<% @agenda.notes.each do |note| %>

<div class="container">
  <div class="row g-1">
    <div class="col-12">
      <div class="colors">
        <p>
          <strong>Descripcion:</strong>
          <%= note.body %>
        </p>
      </div>
    </div>
  </div>
</div>

<% end %>
<br></br>
<h3>New Task:</h3>
<p></p>
<%= form_with model: [ @agenda, @agenda.tasks.build ] do |form| %>
  <p>
    <h5><%= form.label :name %></h5><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
  
  <p>
    <%= form.label :due_date %><br>
    <%= form.date_field :due_date %>
  </p>
  <p>
    <input class="btn btn-outline-dark" <%= form.submit %>
  </p>
<% end %>
<br></br>
<h2>New Note:</h2>
<p></p>
<%= form_with model: [ @agenda, @agenda.notes.build ] do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <input class="btn btn-outline-dark" <%= form.submit %>
  </p>
<% end %>
</div>
</div>
</body>

app/views/categories/_form.html.erb
<%= form_with model: @category do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @category.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
    <% @category.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render "form", category: @category %>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render "form", category: @category %>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CALENDARIO</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
  <nav class="navbar navbar-dark bg-primary">
    <div class="container-fluid">
    <a class="navbar-brand"><b>AGENDA</b></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="http://localhost:3000/">Home</a>
      </li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          User
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        
        </ul>
      </li>
      </ul>
    </div>
  </div>
</nav>

    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with model: [ @agenda, @agenda.notes.build ] do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/notes/note.html.erb
<p>
  <strong>Descripcion:</strong>
  <%= note.body %>
</p>

app/views/tasks/_form.html.erb
<%= form_with model: [ @agenda, @agenda.tasks.build ] do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
  <p>
    <%= form.label :code %><br>
    <%= form.text_area :code %>
  </p>
  <p>
    <%= form.label :due_date %><br>
    <%= form.date_field :due_date %>
  </p>
  <p>
  <%= f.select :category, [ 'Box', 'Cover', 'Poster' ], :prompt => 'Select One' %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/tasks/_task.html.erb
<p>
  <strong>Nombre:</strong>
  <%= task.name %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= task.description %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= task.code %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= task.due_date %>
</p>